using System.Collections.Generic;
using UnityEditor;
using UnityEditor.ShaderGraph;
using UnityEngine;
using UnityEngine.Rendering;
using static Unity.Rendering.Universal.ShaderUtils;

namespace UnityEditor.Rendering.Universal.ShaderGraph
{
    /// <summary>
    /// FIX for the ShaderID.Unknown problem.
    ///
    /// URP validates ShaderGraph materials through Unity.Rendering.Universal.ShaderUtils.UpdateMaterial(),
    /// which switches on the ShaderID stored in the shader's UniversalMetadata. This sub-target has no entry
    /// in URP's internal ShaderID enum, so it reports ShaderID.Unknown and that switch falls through to
    /// "default: break" - nothing happens.
    ///
    /// The consequence was that surface keywords and render state (_SURFACE_TYPE_TRANSPARENT, _ALPHATEST_ON,
    /// _SPECULAR_COLOR, SrcBlend/DstBlend, ZWrite, Cull, render queue) were only ever applied when a human
    /// opened the material inspector. Whether a .mat on disk was correct depended on whether anyone had
    /// clicked on it, which is why the same graph produced different results on different machines.
    ///
    /// This postprocessor reinstates the two automatic paths URP does for its own sub-targets:
    ///   - a material using one of our shaders is imported  -> validate that material
    ///   - one of our shader graphs is reimported           -> validate every material using it
    /// </summary>
    class SimpleLitMaterialPostprocessor : AssetPostprocessor
    {
        // Runs after URP's own MaterialPostprocessor (which uses 0) so we do not fight it.
        public override int GetPostprocessOrder() => 100;

        static readonly ShaderTagId k_MaterialTypeTag = new ShaderTagId("UniversalMaterialType");
        const string k_SimpleLitTagValue = "SimpleLit";

        static void OnPostprocessAllAssets(string[] importedAssets, string[] deletedAssets,
            string[] movedAssets, string[] movedFromAssetPaths)
        {
            var changedShaders = new List<Shader>();
            var materialsToValidate = new List<Material>();

            foreach (var path in importedAssets)
            {
                if (path.EndsWith(".mat", System.StringComparison.OrdinalIgnoreCase))
                {
                    var material = AssetDatabase.LoadAssetAtPath<Material>(path);
                    if (IsSimpleLitShaderGraph(material != null ? material.shader : null))
                        materialsToValidate.Add(material);
                }
                else if (path.EndsWith(".shadergraph", System.StringComparison.OrdinalIgnoreCase))
                {
                    var shader = AssetDatabase.LoadAssetAtPath<Shader>(path);
                    if (IsSimpleLitShaderGraph(shader))
                        changedShaders.Add(shader);
                }
            }

            // A graph changed, so every material using it may need its keywords and blend state redone.
            if (changedShaders.Count > 0)
            {
                foreach (var guid in AssetDatabase.FindAssets("t:Material"))
                {
                    var matPath = AssetDatabase.GUIDToAssetPath(guid);
                    var material = AssetDatabase.LoadAssetAtPath<Material>(matPath);
                    if (material == null || material.shader == null)
                        continue;
                    if (changedShaders.Contains(material.shader) && !materialsToValidate.Contains(material))
                        materialsToValidate.Add(material);
                }
            }

            foreach (var material in materialsToValidate)
            {
                ShaderGraphSimpleLitGUI.UpdateMaterial(material, MaterialUpdateType.ModifiedShader);
                EditorUtility.SetDirty(material);
            }
        }

        /// <summary>
        /// True for shaders generated by this sub-target. Identified by the sub-shader tag the sub-target
        /// writes, rather than by ShaderID, precisely because ShaderID is Unknown here.
        /// </summary>
        static bool IsSimpleLitShaderGraph(Shader shader)
        {
            if (shader == null || shader.subshaderCount == 0)
                return false;
            if (!shader.IsShaderGraphAsset())
                return false;

            for (int i = 0; i < shader.subshaderCount; i++)
            {
                var tag = shader.FindSubshaderTagValue(i, k_MaterialTypeTag);
                if (tag.name == k_SimpleLitTagValue)
                    return true;
            }
            return false;
        }
    }
}
